name: Self-hosted Compiler

on:
  push:
    paths: ['lib/**.ri', 'rivetc/**.py', 'cmd/**.ri']
  pull_request:
    paths: ['lib/**.ri', 'rivetc/**.py', 'cmd/**.ri']
    types: [opened, synchronize]

jobs:
  ubuntu-clang:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile self-hosted compiler
        run: |
          python3 rivetc -C clang -o rivet cmd/
          ./rivet version
          ./rivet build cmd/
          ./rivet test tests/valid

  ubuntu-gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile self-hosted compiler
        run: |
          python3 rivetc -C gcc -o rivet cmd/
          ./rivet version
          ./rivet build cmd/
          ./rivet test tests/valid
